name: Build

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */2 * *'

jobs:
  build:
    runs-on: windows-2019
    steps:
      - run: git config --global core.autocrlf input
      - uses: cygwin/cygwin-install-action@v5
        with:
          packages: gcc-core binutils make
          site: https://mirrors.rit.edu/cygwin/
      - run: git clone --depth=1 --single-branch --branch=master git://git.suckless.org/sbase
      - name: Build
        run: |
          pushd sbase
          make -j5
          copy C:\cygwin\bin\cygwin1.dll .
          popd
      - uses: softprops/action-gh-release@v2
        with:
          name: Continuous
          tag_name: continuous
          files: |
            sbase/cygwin1.dll
            sbase/*.exe
